package model;
// Generated 3 dic. 2023 04:52:31 by Hibernate Tools 4.3.1



/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Integer titulares;
     private Integer suplentes;
     private String directorTecnico;
     private Integer partidosJugados;
     private Integer partidosGanados;
     private Integer partidosPerdidos;
     private Integer partidosEmpatados;
    
    public Equipo() {
    }

	
    public Equipo(String nombre) {
        this.nombre = nombre;
    }
    public Equipo(String nombre, Integer titulares, Integer suplentes, String directorTecnico, Integer partidosJugados, Integer partidosGanados, Integer partidosPerdidos, Integer partidosEmpatados) {
       this.nombre = nombre;
       this.titulares = titulares;
       this.suplentes = suplentes;
       this.directorTecnico = directorTecnico;
       this.partidosJugados = partidosJugados;
       this.partidosGanados = partidosGanados;
       this.partidosPerdidos = partidosPerdidos;
       this.partidosEmpatados = partidosEmpatados;
    }
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTitulares() {
        return this.titulares;
    }
    
    public void setTitulares(Integer titulares) {
        this.titulares = titulares;
    }
    public Integer getSuplentes() {
        return this.suplentes;
    }
    
    public void setSuplentes(Integer suplentes) {
        this.suplentes = suplentes;
    }
    public String getDirectorTecnico() {
        return this.directorTecnico;
    }
    
    public void setDirectorTecnico(String directorTecnico) {
        this.directorTecnico = directorTecnico;
    }
    public Integer getPartidosJugados() {
        return this.partidosJugados;
    }
    
    public void setPartidosJugados(Integer partidosJugados) {
        this.partidosJugados = partidosJugados;
    }
    public Integer getPartidosGanados() {
        return this.partidosGanados;
    }
    
    public void setPartidosGanados(Integer partidosGanados) {
        this.partidosGanados = partidosGanados;
    }
    public Integer getPartidosPerdidos() {
        return this.partidosPerdidos;
    }
    
    public void setPartidosPerdidos(Integer partidosPerdidos) {
        this.partidosPerdidos = partidosPerdidos;
    }
    public Integer getPartidosEmpatados() {
        return this.partidosEmpatados;
    }
    
    public void setPartidosEmpatados(Integer partidosEmpatados) {
        this.partidosEmpatados = partidosEmpatados;
    }




}
